import Head from "next/head";
import NavBar from "@/components/NavBar";
import Login from "pages/auth/Login";

export default function Home() {
  return (
    <>
      <Head>
        <title>Test for Strateg.in</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-slate-100 w-full h-screen ">
        <NavBar />
        <Login />
      </main>
    </>
  );
}
